---
networks:
  frontend:
    external: true
services:
  teleport:
    image: public.ecr.aws/gravitational/teleport-distroless:15.3.6
    container_name: teleport-prod-1
    ports:
      - "3080:3080"
      - "3023:3023"
      - "3024:3024"
      - "3025:3025"
    volumes:
      - ./config:/etc/teleport
      - ./data:/var/lib/teleport
    labels:
      traefik.enable: "true"
      traefik.http.services.teleport-prod-1.loadbalancer.server.port: "3080"
      traefik.http.services.teleport-prod-1.loadbalancer.server.scheme: "https"
      traefik.http.routers.teleport-prod-1-http.entrypoints: "web"
      traefik.http.routers.teleport-prod-1-http.rule: "Host(`${HOST}`)"
      traefik.http.routers.teleport-prod-1-https.entrypoints: "websecure"
      traefik.http.routers.teleport-prod-1-https.rule: "Host(`${HOST}`)"
      traefik.http.routers.teleport-prod-1-https.tls: "true"
      traefik.http.routers.teleport-prod-1-https.tls.certresolver: "cloudflare"
    networks:
      - frontend
    restart: unless-stopped
