networks:
  frontend:
    external: true
  backend:
    external: true

services:
  sharelatex:
    restart: always
    image: sharelatex/sharelatex:latest
    container_name: sharelatex
    volumes:
      - "./data/overleaf:/var/lib/overleaf"
    ports:
      - "8003:80"
    environment:
      GIT_BRIDGE_ENABLED: "false"
      REDIS_HOST: redis
      OVERLEAF_MONGO_URL: mongodb://mongo/sharelatex
      OVERLEAF_REDIS_HOST: redis
      V1_HISTORY_URL: "http://sharelatex:3100/api"
    env_file:
      - ./config/variables.env
    stop_grace_period: 60s
    depends_on:
      redis:
        condition: service_started
      mongo:
        condition: service_healthy
    links:
      - redis
      - mongo
    networks:
      - frontend
      - backend
    labels:
      traefik.enable: "true"
      traefik.http.services.overleaf-prod-1.loadbalancer.server.port: "8083"
      traefik.http.services.overleaf-prod-1.loadbalancer.server.scheme: "http"
      traefik.http.routers.overleaf-prod-1-http.rule: "Host(`${HOST}`)"
      traefik.http.routers.overleaf-prod-1-https.rule: "Host(`${HOST}`)"
      traefik.http.routers.overleaf-prod-1-https.tls: "true"
      traefik.http.routers.overleaf-prod-1-https.tls.certresolver: "cloudflare"

  redis:
    restart: always
    image: redis:latest
    volumes:
      - "./data/redis:/data"
    container_name: redis
    expose:
      - 6379
    networks:
      - backend

  mongo:
    restart: always
    image: mongo:5.0
    command: "--replSet overleaf"
    container_name: mongo
    volumes:
      - "./data/mongo:/data/db"
    expose:
      - 27017
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - backend

  mongoinit:
    restart: "no"
    image: mongo:5.0
    container_name: mongoinit
    depends_on:
      mongo:
        condition: service_healthy
    entrypoint:
      [
        "mongo",
        "--host",
        "mongo:27017",
        "--eval",
        'rs.initiate({ _id: "overleaf", members: [ { _id: 0, host: "mongo:27017" } ] })',
      ]
    networks:
      - backend
