networks:
  frontend:
    external: true
  backend:
    external: true

services:
  guacd:
    container_name: guacamole-guacd-prod-1
    image: guacamole/guacd
    networks:
      - backend
      - frontend
    restart: unless-stopped
    volumes:
      - ./drive:/drive:rw
      - ./record:/record:rw

  postgres:
    container_name: guacamole-postgres-prod-1
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    image: postgres:latest
    networks:
      - backend
    restart: unless-stopped
    volumes:
      - ./init:/docker-entrypoint-initdb.d:z
      - ./data:/var/lib/postgresql/data:Z

  guacamole:
    container_name: guacamole-guacamole-prod-1
    depends_on:
      - guacd
      - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      TOTP_ENABLED: "true"

    image: guacamole/guacamole:latest
    links:
      - guacd
    networks:
      - frontend
      - backend
    ports:
      ## enable next line if not using nginx
      - 8002:8080/tcp # Guacamole is on :8080/guacamole, not /.
    ## enable next line when using nginx
    #- 8080/tcp
    labels:
      traefik.enable: "true"
      traefik.http.services.guacamole-prod-1.loadbalancer.server.port: "8080"
      traefik.http.services.guacamole-prod-1.loadbalancer.server.scheme: "http"
      traefik.http.routers.guacamole-prod-1-http.rule: "Host(`guacamole-prod-1.srv-prod-2.home.anrn.dev`) || Host(mole.anrn.dev)"
      traefik.http.routers.guacamole-prod-1-https.rule: "Host(`guacamole-prod-1.srv-prod-2.home.anrn.dev`) || Host(mole.anrn.dev)"
      traefik.http.routers.guacamole-prod-1-https.tls: "true"
      traefik.http.routers.guacamole-prod-1-https.tls.certresolver: "cloudflare"
    restart: unless-stopped
########### optional ##############
# nginx
#  nginx:
#   container_name: guacamole-nginx-prod-1
#   restart: always
#   image: nginx:latest
#   volumes:
#   - /usr/docker/guacamole_data/nginx/templates:/etc/nginx/templates:ro
#   - /usr/docker/guacamole_data/nginx/ssl/self.cert:/etc/nginx/ssl/self.cert:ro
#   - /usr/docker/guacamole_data/nginx/ssl/self-ssl.key:/etc/nginx/ssl/self-ssl.key:ro
#   - 27022:443
##   ports:
#   links:
#   - guacamole
#    - frontend
##   networks:
#    - backend
